# @package _global_

defaults:
  - /model/falcon/common.yaml
  - _self_

model:
  name: falcon-2.7b
  hidden_size: 2560
  intermediate_size: 10240
  num_hidden_layers: 32
  num_attention_heads: 32
  num_heads_kv: ~