# @package _global_

defaults:
  - /model/falcon/common.yaml
  - _self_

model:
  name: falcon-22b
  hidden_size: 6144
  intermediate_size: 24576
  num_hidden_layers: 48
  num_attention_heads: 64
  num_heads_kv: ~