# @package _global_

defaults:
  - /model/gpt2/common.yaml
  - _self_

model:
  name: gpt2-H5120-L80
  hidden_size: 5120
  intermediate_size: 20480
  num_hidden_layers: 80
  num_attention_heads: 40
  num_heads_kv: ~