# @package _global_

defaults:
  - /model/llama/common.yaml
  - _self_

model:
  name: llama-13b
  hidden_size: 5120
  intermediate_size: 13824
  num_hidden_layers: 40
  num_attention_heads: 40
  num_heads_kv: ~