# @package _global_

defaults:
  - /model/llama/common.yaml
  - _self_

model:
  name: llama-20b
  hidden_size: 6144
  intermediate_size: 16384
  num_hidden_layers: 44
  num_attention_heads: 64
  num_heads_kv: ~