# @package _global_

defaults:
  - /model/llama/common.yaml
  - _self_

model:
  name: llama-70b
  hidden_size: 8192
  intermediate_size: 28672
  num_hidden_layers: 80
  num_attention_heads: 64
  num_heads_kv: ~