# @package _global_

defaults:
  - /model/llama/common.yaml
  - _self_

model:
  name: llama-7b
  hidden_size: 4096
  intermediate_size: 11008
  num_hidden_layers: 32
  num_attention_heads: 32
  num_heads_kv: ~